config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/update'
  get 'cards/show'
  root 'pages#home'

  resources :menus
  resources :categories
  resources :pages, only: [:home, :show]
  resources :order_items, only: [:create, :update, :destroy]
  scope :order_items do
    get '/order_items/:id' => 'order_items#destroy', as: :destroy_order_item
    get '/checkout' => 'order_items#checkout', as: :checkout
  end


  resources :card, only: [:show]
  resources :dashboard, only: [:index, :update, :show]
  scope :dashboard do
    put '/dashboard/:id' => 'dashboard#update', as: :update_order
    get '/dashboard/:id' => 'dashboard#show', as: :show_order
  end

  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/home.html.erb
<h1>Gigih Family Cathering</h1>

<% if current_user %>
  <h2>Selamat Datang di Gigih Family Cathering <%= current_user.username %></h2>

    <% if current_user.admin? %>
        <%= link_to 'Menu', menus_path %> = 
        <%= link_to 'Kategori', categories_path %>  -
        <%= link_to 'Dashboard', dashboard_index_url %> 
        <br><br>
    <% end %>

    <% if current_user.user? %>
        <h1>Daftar Menu</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nama</th>
                    <th>Harga</th>
                    <th>Kategori</th>
                    <th colspan='4' ></th>
                </tr>
            </thead>
            <tbody>
                <% @menus.each do |menu| %>
                    <tr>
                        <td><%= menu.name %></td>
                        <td>Rp. <%= menu.price %></td>
                        <% @categories.each do |category| %>
                            <% if category.id == menu.category_id %>
                                <td><%= category.name %></td>
                            <% end %>
                        <% end %>
                        <td><%= link_to "Show", page_url(menu) %></td>

                        <td>
                            <%= form_for @order_item do |f| %>
                                <%= f.hidden_field :menu_id, value: menu.id %>
                                <%= f.hidden_field :email, value: current_user.email %>
                                <%= f.number_field :quantity, min: 1, value: 1 %>
                                <%= f.submit "Add to cart", class: "btn btn-primary" %>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>

        <br>

        <%= link_to"#{current_order.order_items.count} item(s) in cart total Rp.#{current_order.subtotal}", cards_show_url %>

    <% end %>


    <br><br><br>
    <%= link_to 'Log out', destroy_user_session_path,  method: :delete %>
<% else %>
    <%= link_to 'Login', new_user_session_path %>
    <br>
    <%= link_to 'Sign up', new_user_registration_path %>
<% end %>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @menu %>

<div>
  <%= link_to "Back", root_path %>
</div>