config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/update'
  get 'cards/show'
  root 'pages#home'

  resources :menus
  resources :categories
  resources :pages, only: [:home, :show]
  resources :order_items, only: [:create, :update, :destroy]
  scope :order_items do
    get '/order_items/:id' => 'order_items#destroy', as: :destroy_order_item
    get '/checkout' => 'order_items#checkout', as: :checkout
  end


  resources :card, only: [:show]
  resources :dashboard, only: [:index, :update, :show]
  scope :dashboard do
    put '/dashboard/:id' => 'dashboard#update', as: :update_order
    get '/dashboard/:id' => 'dashboard#show', as: :show_order
  end

  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/show.html.erb
<h1>Keranjang</h1>

<% if @order_items.empty? %>
    <p>Keranjangmu Kosong</p>
<% else %>
    <% @order_items.each do |order_item| %>
    <h1> <%= order_item.menu.name %> </h1>
        <h3>Rp.<%= order_item.menu.price %> </h3>

        <%= form_for order_item  do |f| %>
            <%= f.hidden_field :menu_id, value: order_item.menu.id %>
            <%= f.number_field :quantity, min: 1, value: order_item.quantity.to_i %>
            <%= f.submit "Update Card", class: "btn btn-primary" %>

            <%= link_to "Delete", destroy_order_item_path(order_item), method: :delete , data: { confirm: 'Are you sure?' } %>
        <% end %>

        <h4> Subtotal: Rp.<%= order_item.total %> </h4>


    <% end %>

    <br><br><br>
    <h2> Total: Rp.<%= current_order.subtotal %> </h2>
    <br>

    <%= link_to 'Checkout', checkout_path, class: "btn btn-primary" %>

<% end %>




<br>
<%= link_to "Back", root_path %>